.TH BITCALC 1 "September 2026" "v2.0.0" "User Commands"
.SH NAME
bitcalc \- Advanced Base Converter, Binary Arithmetic & MCU Bitwise Utility
.SH SYNOPSIS
.B bitcalc
[\fIFLAGS\fR] <\fINUMBER\fR>
.br
.B bitcalc
[\fIFLAGS\fR] <\fINUMBER\fR> <\fIOPERATOR\fR> <\fINUMBER\fR>
.br
.B bitcalc
[\fIFLAGS\fR] <\fINUMBER\fR> <\fIUNARY_OPERATOR\fR> [\fIFLAGS\fR]
.br
.B echo
"<\fIEXPPRESSION\fR>" | bitcalc [\fIFLAGS\fR]
.br
.SH DESCRIPTION
bitcalc is a hardware engineering toolkit for executing binary arithmetic, base conversions, and step-by-step visualizations.
.SH FLAGS
.TP
\fB\-f\fR, \fB\-\-from\fR \fIBASE\fR
Input base: bin (2), oct (8), dec (10), hex (16)
.TP
\fB\-t\fR, \fB\-\-to\fR \fIBASE\fR
Output base: bin, oct, dec, hex, bcd, gray
.TP
\fB\-w\fR, \fB\-\-width\fR \fIBITS\fR
Register bit-width for bounds and padding. Defualt: 8
.TP
\fB\-\-prec\fR \fIBITS\fR
Precision depth for fractional binary. Default: 8
.TP
\fB\-q\fR, \fB\-\-quiet\fR 
Output only the final value (ideal for pipelines)
.TP
\fB\-i\fR, \fB\-\-interactive\fR 
Launch the REPL interactive shell
.TP
\fB\-h\fR, \fB\-\-help\fR 
Display this man page
.SH OPERATORS
.B Binary Maths;
ADD, SUB, MUL, DIV
.br
.B Bitwise Logic:
AND, OR, XOR, NAND, NOR, LSHIFT, RSHIFT
.br
.B MCU Manipulation:
ROL, ROR
.br
.B Unary Operations:
NOT, 1COMP, 2COMP, BSWAP, POPCNT
.br
.SH EXAMPLES
.TP
Convert a fractional decimal to binary:
bitcalc \-\-from dec \-\-to bin 13.625
.TP
Perform a 2s compliment on a negative decimal number and convert the final answer to hexadecimal:
bitcalc \-\-width 16 2COMP \-10 \-\-to hex
.TP
Perform a POPCOUNT on a binary value:
bitcalc 0b10110110 POPCNT
.TP
Perfom binary addition:
bitcalc 0b1011 ADD 0b0110
.TP
Convert a decimal to Binary Coded Decimal:
bitcalc \-\-to bcd 94
.SH AUTHOR
.B
Nyang'ada Stone Bradley
.br
