#!/usr/bin/bash
set -e

case "$1" in
	configure)
		echo "Compiling bitcalc binary locally for $(uname -m)"
		mkdir -p /usr/bin

		shc -f /usr/share/bitcalc/bitcalc_source -o /usr/bin/bitcalc
		chmod 755 /usr/bin/bitcalc

		rm -f /usr/share/bitcalc/bitcalc_source.x.c
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unkown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
