name: Build, Sign, Test and Publish APT Repository

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools and shc
        run: |
          sudo apt-get update 
          sudo apt-get install -y dpkg-dev gzip apt-utils shc gcc build-essential gnupg

      - name: Import GPG Private Key
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      - name: Compile and Build Debian Package
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          mkdir -p build_dir/usr/bin
          mkdir -p build_dir/usr/share/man/man1
          mkdir -p build_dir/DEBIAN

          shc -f bitcalc_source -o build_dir/usr/bin/bitcalc
          chmod 755 build_dir/usr/bin/bitcalc
          rm -f bitcalc_source.x.c

          sed "s/{{VERSION}}/$VERSION/g" control.template > build_dir/DEBIAN/control

          if [ -f "bitcalc.1" ]; then
            cp bitcalc.1 build_dir/usr/share/man/man1/bitcalc.1
            gzip -9 -f build_dir/usr/share/man/man1/bitcalc.1
            chmod 644 build_dir/usr/share/man/man1/bitcalc.1.gz
          fi

          dpkg-deb --root-owner-group --build build_dir bitcalc_${VERSION}_all.deb

      - name: Build and Sign APT Repository Structure
        run: |
          REPO_DIR="apt-repo"
          MAIN_DIR="$REPO_DIR/dists/stable/main/binary-amd64
          POOL_DIR="$REPO_DIR/pool/main

          mkdir -p "$MAIN_DIR"
          mkdir -p "$POOL_DIR"
`
          cp bitcalc-pub.asc "$REPO_DIR/"

          mv *.deb "$POOL_DIR"

          cd "$REPO_DIR"

          dpkg-scanpackages --arch amd64 pool/main > dists/stable/main/binary-amd64/Packages
          cat dists/stable/main/binary-amd64/Packages | gzip -9c > dists/stable/main/binary-amd64/Packages.gz

          cat <<EOF > apt-release.conf
          APT::FTPArchive::Release::Origin "Bitcalc";
          APT::FTPArchive::Release::Suite "stable";
          APT::FTPArchive::Release::Codename "stable";
          APT::FTPArchive::Release::Architectures "amd64";
          APT::FTPArchive::Release::Components "main";
          EOF

          apt-ftparchive -c apt-release.conf release dists/stable > dists/stable/Release

          gpg --default-key "ridddle5050@gmail.com" -abs -o dists/stable/Release.gpg dists/stable/Release
          gpg --defualt-key "ridddle5050@gmail.com" --clearsign -o dists/stable/InRelease dists/stable/Release

      - name: Test Installed Package locally
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Installing the built package locally for testing..."
          cd apt-repo
          python3 -m http.server 8080 &
          SERVER_PID=$!
          sleep 2

          echo "Simulating user environment"
          sudo cp bitcalc-pub.asc /etc/apt/keyrings/bitcacl.asc
          echo "deb [arch-amd64 signed-by=/etc/keyrings/bitcalc.asc] http://localhost:8080/ stable main" | sudo tee /etc/apt/sources.list.d//bitcalc-test.list

          sudo apt-get update
          sudo apt-get install -y bitcalc

          echo "Testing binary execution"
          bitcalc --help > /dev/null

          echo "Testing mathematical output..."
          OUTPUT=$(bitcalc -q 10 ADD 2)
          if [ "$OUTPUT" != "12" ]; then
            echo "Test failed: Expected 12, got $OUTPUT"
            exit
          fi

          echo "Testing Base Conversion..."
          OUTPUT=$(bitcalc -q -t bin 0xA)
          if [ "$OUTPUT" != "0b00001010" ]; then
            echo "Test Failed: Expected 0b00001010 got $OUTPUT"
            exit 1
          fi

          echo "All structural and logic tests passed successfully!"
          kill $SERVER_ID

      - name: Deploy APT Repo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apt-repo
          keep_files: true
